// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contacts.proto

package io.adetalhouet.directory.grpc;

public final class Contacts {
  private Contacts() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_adetalhouet_directory_PersonData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_adetalhouet_directory_PersonData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_adetalhouet_directory_Identifier_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_adetalhouet_directory_Identifier_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_adetalhouet_directory_Person_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_adetalhouet_directory_Person_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_adetalhouet_directory_PersonDatabase_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_adetalhouet_directory_PersonDatabase_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016contacts.proto\022\030io.adetalhouet.directo" +
      "ry\032\034google/api/annotations.proto\032\033google" +
      "/protobuf/empty.proto\"\256\001\n\nPersonData\022\020\n\010" +
      "survived\030\001 \001(\t\022\026\n\016passengerClass\030\002 \001(\005\022\014" +
      "\n\004name\030\003 \001(\t\022\013\n\003sex\030\004 \001(\t\022\013\n\003age\030\005 \001(\005\022\037" +
      "\n\027siblingsOrSpousesAboard\030\006 \001(\005\022\037\n\027paren" +
      "tsOrChildrenAboard\030\007 \001(\005\022\014\n\004fare\030\010 \001(\001\"\032" +
      "\n\nIdentifier\022\014\n\004uuid\030\001 \001(\t\"P\n\006Person\022\014\n\004" +
      "uuid\030\001 \001(\t\0228\n\npersonData\030\002 \001(\0132$.io.adet" +
      "alhouet.directory.PersonData\"B\n\016PersonDa" +
      "tabase\0220\n\006person\030\001 \003(\0132 .io.adetalhouet." +
      "directory.Person2\264\002\n\016ContactService\022[\n\006C" +
      "reate\022 .io.adetalhouet.directory.Person\032" +
      "\026.google.protobuf.Empty\"\027\202\323\344\223\002\021\"\014/v1/con" +
      "tacts:\001*\022Y\n\005Lists\022\026.google.protobuf.Empt" +
      "y\032 .io.adetalhouet.directory.Person\"\024\202\323\344" +
      "\223\002\016\022\014/v1/contacts0\001\022j\n\003Get\022$.io.adetalho" +
      "uet.directory.Identifier\032 .io.adetalhoue" +
      "t.directory.Person\"\033\202\323\344\223\002\025\022\023/v1/contacts" +
      "/{uuid}B!\n\035io.adetalhouet.directory.grpc" +
      "P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_io_adetalhouet_directory_PersonData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_adetalhouet_directory_PersonData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_adetalhouet_directory_PersonData_descriptor,
        new java.lang.String[] { "Survived", "PassengerClass", "Name", "Sex", "Age", "SiblingsOrSpousesAboard", "ParentsOrChildrenAboard", "Fare", });
    internal_static_io_adetalhouet_directory_Identifier_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_adetalhouet_directory_Identifier_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_adetalhouet_directory_Identifier_descriptor,
        new java.lang.String[] { "Uuid", });
    internal_static_io_adetalhouet_directory_Person_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_io_adetalhouet_directory_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_adetalhouet_directory_Person_descriptor,
        new java.lang.String[] { "Uuid", "PersonData", });
    internal_static_io_adetalhouet_directory_PersonDatabase_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_io_adetalhouet_directory_PersonDatabase_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_adetalhouet_directory_PersonDatabase_descriptor,
        new java.lang.String[] { "Person", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
