// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contacts.proto

package io.adetalhouet.directory.grpc;

public interface IdentifierOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.adetalhouet.directory.Identifier)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string uuid = 1;</code>
   * @return The uuid.
   */
  java.lang.String getUuid();
  /**
   * <code>string uuid = 1;</code>
   * @return The bytes for uuid.
   */
  com.google.protobuf.ByteString
      getUuidBytes();
}
