// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contacts.proto

package io.adetalhouet.directory.grpc;

public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.adetalhouet.directory.Person)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string uuid = 1;</code>
   * @return The uuid.
   */
  java.lang.String getUuid();
  /**
   * <code>string uuid = 1;</code>
   * @return The bytes for uuid.
   */
  com.google.protobuf.ByteString
      getUuidBytes();

  /**
   * <code>.io.adetalhouet.directory.PersonData personData = 2;</code>
   * @return Whether the personData field is set.
   */
  boolean hasPersonData();
  /**
   * <code>.io.adetalhouet.directory.PersonData personData = 2;</code>
   * @return The personData.
   */
  io.adetalhouet.directory.grpc.PersonData getPersonData();
  /**
   * <code>.io.adetalhouet.directory.PersonData personData = 2;</code>
   */
  io.adetalhouet.directory.grpc.PersonDataOrBuilder getPersonDataOrBuilder();
}
