// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contacts.proto

package io.adetalhouet.directory.grpc;

public interface PersonDatabaseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.adetalhouet.directory.PersonDatabase)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .io.adetalhouet.directory.Person person = 1;</code>
   */
  java.util.List<io.adetalhouet.directory.grpc.Person> 
      getPersonList();
  /**
   * <code>repeated .io.adetalhouet.directory.Person person = 1;</code>
   */
  io.adetalhouet.directory.grpc.Person getPerson(int index);
  /**
   * <code>repeated .io.adetalhouet.directory.Person person = 1;</code>
   */
  int getPersonCount();
  /**
   * <code>repeated .io.adetalhouet.directory.Person person = 1;</code>
   */
  java.util.List<? extends io.adetalhouet.directory.grpc.PersonOrBuilder> 
      getPersonOrBuilderList();
  /**
   * <code>repeated .io.adetalhouet.directory.Person person = 1;</code>
   */
  io.adetalhouet.directory.grpc.PersonOrBuilder getPersonOrBuilder(
      int index);
}
