// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contacts.proto

package io.adetalhouet.directory.grpc;

/**
 * Protobuf type {@code io.adetalhouet.directory.Person}
 */
public  final class Person extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:io.adetalhouet.directory.Person)
    PersonOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Person.newBuilder() to construct.
  private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Person() {
    uuid_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Person();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Person(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            uuid_ = s;
            break;
          }
          case 18: {
            io.adetalhouet.directory.grpc.PersonData.Builder subBuilder = null;
            if (personData_ != null) {
              subBuilder = personData_.toBuilder();
            }
            personData_ = input.readMessage(io.adetalhouet.directory.grpc.PersonData.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(personData_);
              personData_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.adetalhouet.directory.grpc.Contacts.internal_static_io_adetalhouet_directory_Person_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.adetalhouet.directory.grpc.Contacts.internal_static_io_adetalhouet_directory_Person_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.adetalhouet.directory.grpc.Person.class, io.adetalhouet.directory.grpc.Person.Builder.class);
  }

  public static final int UUID_FIELD_NUMBER = 1;
  private volatile java.lang.Object uuid_;
  /**
   * <code>string uuid = 1;</code>
   * @return The uuid.
   */
  public java.lang.String getUuid() {
    java.lang.Object ref = uuid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      uuid_ = s;
      return s;
    }
  }
  /**
   * <code>string uuid = 1;</code>
   * @return The bytes for uuid.
   */
  public com.google.protobuf.ByteString
      getUuidBytes() {
    java.lang.Object ref = uuid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      uuid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PERSONDATA_FIELD_NUMBER = 2;
  private io.adetalhouet.directory.grpc.PersonData personData_;
  /**
   * <code>.io.adetalhouet.directory.PersonData personData = 2;</code>
   * @return Whether the personData field is set.
   */
  public boolean hasPersonData() {
    return personData_ != null;
  }
  /**
   * <code>.io.adetalhouet.directory.PersonData personData = 2;</code>
   * @return The personData.
   */
  public io.adetalhouet.directory.grpc.PersonData getPersonData() {
    return personData_ == null ? io.adetalhouet.directory.grpc.PersonData.getDefaultInstance() : personData_;
  }
  /**
   * <code>.io.adetalhouet.directory.PersonData personData = 2;</code>
   */
  public io.adetalhouet.directory.grpc.PersonDataOrBuilder getPersonDataOrBuilder() {
    return getPersonData();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getUuidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uuid_);
    }
    if (personData_ != null) {
      output.writeMessage(2, getPersonData());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getUuidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uuid_);
    }
    if (personData_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPersonData());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.adetalhouet.directory.grpc.Person)) {
      return super.equals(obj);
    }
    io.adetalhouet.directory.grpc.Person other = (io.adetalhouet.directory.grpc.Person) obj;

    if (!getUuid()
        .equals(other.getUuid())) return false;
    if (hasPersonData() != other.hasPersonData()) return false;
    if (hasPersonData()) {
      if (!getPersonData()
          .equals(other.getPersonData())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + UUID_FIELD_NUMBER;
    hash = (53 * hash) + getUuid().hashCode();
    if (hasPersonData()) {
      hash = (37 * hash) + PERSONDATA_FIELD_NUMBER;
      hash = (53 * hash) + getPersonData().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.adetalhouet.directory.grpc.Person parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.adetalhouet.directory.grpc.Person parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.adetalhouet.directory.grpc.Person parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.adetalhouet.directory.grpc.Person parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.adetalhouet.directory.grpc.Person parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.adetalhouet.directory.grpc.Person parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.adetalhouet.directory.grpc.Person parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.adetalhouet.directory.grpc.Person parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.adetalhouet.directory.grpc.Person parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.adetalhouet.directory.grpc.Person parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.adetalhouet.directory.grpc.Person parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.adetalhouet.directory.grpc.Person parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.adetalhouet.directory.grpc.Person prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code io.adetalhouet.directory.Person}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.adetalhouet.directory.Person)
      io.adetalhouet.directory.grpc.PersonOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.adetalhouet.directory.grpc.Contacts.internal_static_io_adetalhouet_directory_Person_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.adetalhouet.directory.grpc.Contacts.internal_static_io_adetalhouet_directory_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.adetalhouet.directory.grpc.Person.class, io.adetalhouet.directory.grpc.Person.Builder.class);
    }

    // Construct using io.adetalhouet.directory.grpc.Person.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      uuid_ = "";

      if (personDataBuilder_ == null) {
        personData_ = null;
      } else {
        personData_ = null;
        personDataBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.adetalhouet.directory.grpc.Contacts.internal_static_io_adetalhouet_directory_Person_descriptor;
    }

    @java.lang.Override
    public io.adetalhouet.directory.grpc.Person getDefaultInstanceForType() {
      return io.adetalhouet.directory.grpc.Person.getDefaultInstance();
    }

    @java.lang.Override
    public io.adetalhouet.directory.grpc.Person build() {
      io.adetalhouet.directory.grpc.Person result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.adetalhouet.directory.grpc.Person buildPartial() {
      io.adetalhouet.directory.grpc.Person result = new io.adetalhouet.directory.grpc.Person(this);
      result.uuid_ = uuid_;
      if (personDataBuilder_ == null) {
        result.personData_ = personData_;
      } else {
        result.personData_ = personDataBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.adetalhouet.directory.grpc.Person) {
        return mergeFrom((io.adetalhouet.directory.grpc.Person)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.adetalhouet.directory.grpc.Person other) {
      if (other == io.adetalhouet.directory.grpc.Person.getDefaultInstance()) return this;
      if (!other.getUuid().isEmpty()) {
        uuid_ = other.uuid_;
        onChanged();
      }
      if (other.hasPersonData()) {
        mergePersonData(other.getPersonData());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.adetalhouet.directory.grpc.Person parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.adetalhouet.directory.grpc.Person) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object uuid_ = "";
    /**
     * <code>string uuid = 1;</code>
     * @return The uuid.
     */
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uuid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string uuid = 1;</code>
     * @return The bytes for uuid.
     */
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string uuid = 1;</code>
     * @param value The uuid to set.
     * @return This builder for chaining.
     */
    public Builder setUuid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      uuid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string uuid = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUuid() {
      
      uuid_ = getDefaultInstance().getUuid();
      onChanged();
      return this;
    }
    /**
     * <code>string uuid = 1;</code>
     * @param value The bytes for uuid to set.
     * @return This builder for chaining.
     */
    public Builder setUuidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      uuid_ = value;
      onChanged();
      return this;
    }

    private io.adetalhouet.directory.grpc.PersonData personData_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.adetalhouet.directory.grpc.PersonData, io.adetalhouet.directory.grpc.PersonData.Builder, io.adetalhouet.directory.grpc.PersonDataOrBuilder> personDataBuilder_;
    /**
     * <code>.io.adetalhouet.directory.PersonData personData = 2;</code>
     * @return Whether the personData field is set.
     */
    public boolean hasPersonData() {
      return personDataBuilder_ != null || personData_ != null;
    }
    /**
     * <code>.io.adetalhouet.directory.PersonData personData = 2;</code>
     * @return The personData.
     */
    public io.adetalhouet.directory.grpc.PersonData getPersonData() {
      if (personDataBuilder_ == null) {
        return personData_ == null ? io.adetalhouet.directory.grpc.PersonData.getDefaultInstance() : personData_;
      } else {
        return personDataBuilder_.getMessage();
      }
    }
    /**
     * <code>.io.adetalhouet.directory.PersonData personData = 2;</code>
     */
    public Builder setPersonData(io.adetalhouet.directory.grpc.PersonData value) {
      if (personDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        personData_ = value;
        onChanged();
      } else {
        personDataBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.io.adetalhouet.directory.PersonData personData = 2;</code>
     */
    public Builder setPersonData(
        io.adetalhouet.directory.grpc.PersonData.Builder builderForValue) {
      if (personDataBuilder_ == null) {
        personData_ = builderForValue.build();
        onChanged();
      } else {
        personDataBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.io.adetalhouet.directory.PersonData personData = 2;</code>
     */
    public Builder mergePersonData(io.adetalhouet.directory.grpc.PersonData value) {
      if (personDataBuilder_ == null) {
        if (personData_ != null) {
          personData_ =
            io.adetalhouet.directory.grpc.PersonData.newBuilder(personData_).mergeFrom(value).buildPartial();
        } else {
          personData_ = value;
        }
        onChanged();
      } else {
        personDataBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.io.adetalhouet.directory.PersonData personData = 2;</code>
     */
    public Builder clearPersonData() {
      if (personDataBuilder_ == null) {
        personData_ = null;
        onChanged();
      } else {
        personData_ = null;
        personDataBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.io.adetalhouet.directory.PersonData personData = 2;</code>
     */
    public io.adetalhouet.directory.grpc.PersonData.Builder getPersonDataBuilder() {
      
      onChanged();
      return getPersonDataFieldBuilder().getBuilder();
    }
    /**
     * <code>.io.adetalhouet.directory.PersonData personData = 2;</code>
     */
    public io.adetalhouet.directory.grpc.PersonDataOrBuilder getPersonDataOrBuilder() {
      if (personDataBuilder_ != null) {
        return personDataBuilder_.getMessageOrBuilder();
      } else {
        return personData_ == null ?
            io.adetalhouet.directory.grpc.PersonData.getDefaultInstance() : personData_;
      }
    }
    /**
     * <code>.io.adetalhouet.directory.PersonData personData = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.adetalhouet.directory.grpc.PersonData, io.adetalhouet.directory.grpc.PersonData.Builder, io.adetalhouet.directory.grpc.PersonDataOrBuilder> 
        getPersonDataFieldBuilder() {
      if (personDataBuilder_ == null) {
        personDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.adetalhouet.directory.grpc.PersonData, io.adetalhouet.directory.grpc.PersonData.Builder, io.adetalhouet.directory.grpc.PersonDataOrBuilder>(
                getPersonData(),
                getParentForChildren(),
                isClean());
        personData_ = null;
      }
      return personDataBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:io.adetalhouet.directory.Person)
  }

  // @@protoc_insertion_point(class_scope:io.adetalhouet.directory.Person)
  private static final io.adetalhouet.directory.grpc.Person DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.adetalhouet.directory.grpc.Person();
  }

  public static io.adetalhouet.directory.grpc.Person getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Person>
      PARSER = new com.google.protobuf.AbstractParser<Person>() {
    @java.lang.Override
    public Person parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Person(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Person> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Person> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.adetalhouet.directory.grpc.Person getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

