// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contacts.proto

package io.adetalhouet.directory.grpc;

public interface PersonDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.adetalhouet.directory.PersonData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string survived = 1;</code>
   * @return The survived.
   */
  java.lang.String getSurvived();
  /**
   * <code>string survived = 1;</code>
   * @return The bytes for survived.
   */
  com.google.protobuf.ByteString
      getSurvivedBytes();

  /**
   * <code>int32 passengerClass = 2;</code>
   * @return The passengerClass.
   */
  int getPassengerClass();

  /**
   * <code>string name = 3;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string sex = 4;</code>
   * @return The sex.
   */
  java.lang.String getSex();
  /**
   * <code>string sex = 4;</code>
   * @return The bytes for sex.
   */
  com.google.protobuf.ByteString
      getSexBytes();

  /**
   * <code>int32 age = 5;</code>
   * @return The age.
   */
  int getAge();

  /**
   * <code>int32 siblingsOrSpousesAboard = 6;</code>
   * @return The siblingsOrSpousesAboard.
   */
  int getSiblingsOrSpousesAboard();

  /**
   * <code>int32 parentsOrChildrenAboard = 7;</code>
   * @return The parentsOrChildrenAboard.
   */
  int getParentsOrChildrenAboard();

  /**
   * <code>double fare = 8;</code>
   * @return The fare.
   */
  double getFare();
}
